### ISSUE TITLE
fails to run netdata

### ISSUE THREAD

**Issue by lianghu** [wbx-github/uclibc-ng#1]
There is brk and  exiting abnormal.

root@OpenWrt:/# strace netdata
execve("/usr/sbin/netdata", ["netdata"], [/* 10 vars */]) = 0
readlinkat(AT_FDCWD, "/proc/self/exe", "/usr/sbin/netdata", 4096) = 17
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0xb6fd3000
stat("/etc/ld.so.cache", 0xbeb82ad0)    = -1 ENOENT (No such file or directory)
open("/lib/libm.so.0", O_RDONLY)        = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=36908, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0xb6fd2000
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\220\26\0\0004\0\0\0"..., 4096) = 4096
mmap2(NULL, 73728, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6fb5000
mmap2(0xb6fb5000, 34436, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0xb6fb5000
mmap2(0xb6fc5000, 4140, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x8000) = 0xb6fc5000
close(3)                                = 0
munmap(0xb6fd2000, 4096)                = 0
open("/lib/libz.so.1", O_RDONLY)        = -1 ENOENT (No such file or directory)
open("/usr/lib/libz.so.1", O_RDONLY)    = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=66217, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0xb6fd2000
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\260\25\0\0004\0\0\0"..., 4096) = 4096
mmap2(NULL, 69632, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6fa4000
mmap2(0xb6fa4000, 65288, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0xb6fa4000
mmap2(0xb6fb4000, 681, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x10000) = 0xb6fb4000
close(3)                                = 0
munmap(0xb6fd2000, 4096)                = 0
open("/lib/libuuid.so.1", O_RDONLY)     = -1 ENOENT (No such file or directory)
open("/usr/lib/libuuid.so.1", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=8664, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0xb6fd2000
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\344\r\0\0004\0\0\0"..., 4096) = 4096
mmap2(NULL, 45056, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6f99000
mmap2(0xb6f99000, 8040, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0xb6f99000
mmap2(0xb6fa3000, 472, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x2000) = 0xb6fa3000
close(3)                                = 0
munmap(0xb6fd2000, 4096)                = 0
open("/lib/libgcc_s.so.1", O_RDONLY)    = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=41819, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0xb6fd2000
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\320;\0\0004\0\0\0"..., 4096) = 4096
mmap2(NULL, 77824, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6f86000
mmap2(0xb6f86000, 41280, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0xb6f86000
mmap2(0xb6f98000, 859, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0xa000) = 0xb6f98000
close(3)                                = 0
munmap(0xb6fd2000, 4096)                = 0
open("/lib/libpthread.so.0", O_RDONLY)  = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=65971, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0xb6fd2000
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\200F\0\0004\0\0\0"..., 4096) = 4096
mmap2(NULL, 110592, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6f6b000
mmap2(0xb6f6b000, 64464, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0xb6f6b000
mmap2(0xb6f82000, 4531, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0xf000) = 0xb6f82000
mmap2(0xb6f84000, 4736, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xb6f84000
close(3)                                = 0
munmap(0xb6fd2000, 4096)                = 0
open("/lib/libc.so.0", O_RDONLY)        = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=295883, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0xb6fd2000
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\260\235\0\0004\0\0\0"..., 4096) = 4096
mmap2(NULL, 344064, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6f17000
mmap2(0xb6f17000, 291532, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0xb6f17000
mmap2(0xb6f66000, 5067, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x47000) = 0xb6f66000
mmap2(0xb6f68000, 10160, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xb6f68000
close(3)                                = 0
munmap(0xb6fd2000, 4096)                = 0
open("/lib/libc.so.0", O_RDONLY)        = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=295883, ...}) = 0
close(3)                                = 0
open("/lib/libc.so.0", O_RDONLY)        = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=295883, ...}) = 0
close(3)                                = 0
open("/lib/libgcc_s.so.1", O_RDONLY)    = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=41819, ...}) = 0
close(3)                                = 0
open("/lib/libgcc_s.so.1", O_RDONLY)    = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=41819, ...}) = 0
close(3)                                = 0
open("/lib/libc.so.0", O_RDONLY)        = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=295883, ...}) = 0
close(3)                                = 0
open("/lib/libc.so.0", O_RDONLY)        = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=295883, ...}) = 0
close(3)                                = 0
stat("/lib/ld-uClibc.so.0", {st_mode=S_IFREG|0755, st_size=28677, ...}) = 0
open("/lib/libdl.so.0", O_RDONLY)       = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=12469, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0xb6fd2000
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\0\f\0\0004\0\0\0"..., 4096) = 4096
mmap2(NULL, 49152, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6f0b000
mmap2(0xb6f0b000, 8177, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0xb6f0b000
mmap2(0xb6f15000, 4277, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x2000) = 0xb6f15000
close(3)                                = 0
munmap(0xb6fd2000, 4096)                = 0
open("/lib/libc.so.0", O_RDONLY)        = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=295883, ...}) = 0
close(3)                                = 0
open("/lib/libc.so.0", O_RDONLY)        = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=295883, ...}) = 0
close(3)                                = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0xb6fd2000
set_tls(0xb6fd2490, 0xb6fd2b30, 0xb6fd2b38, 0xb6fd2490, 0xb6fd5f74) = 0
mprotect(0xb6fc5000, 4096, PROT_READ)   = 0
mprotect(0xb6f82000, 4096, PROT_READ)   = 0
mprotect(0xb6f66000, 4096, PROT_READ)   = 0
mprotect(0xb6fd5000, 4096, PROT_READ)   = 0
mprotect(0xb6f15000, 4096, PROT_READ)   = 0
set_tid_address(0xb6fd2068)             = 2011
set_robust_list(0xb6fd2070, 12)         = 0
rt_sigaction(SIGRTMIN, {0xb6f736f8, [], SA_SIGINFO|0x4000000}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0xb6f735b4, [], SA_RESTART|SA_SIGINFO|0x4000000}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM_INFINITY}) = 0
ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B115200 opost isig icanon echo ...}) = 0
ioctl(1, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B115200 opost isig icanon echo ...}) = 0
brk(0)                                  = 0x79000
brk(0x7a000)                            = 0x7a000
open("/etc/netdata/netdata.conf", O_RDONLY) = 3
ioctl(3, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, 0xbeb807d4) = -1 ENOTTY (Inappropriate ioctl for device)
brk(0x7b000)                            = 0x7b000
read(3, "[global]\n\trun as user = nobody\n\t"..., 4096) = 250
read(3, "", 4096)                       = 0
close(3)                                = 0
chdir("/etc/netdata")                   = 0
open("/etc/netdata", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat64(3, {st_mode=S_IFDIR|0755, st_size=80, ...}) = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
close(3)                                = 0
chdir("/usr/lib/netdata/plugins.d")     = 0
open("/usr/lib/netdata/plugins.d", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat64(3, {st_mode=S_IFDIR|0755, st_size=245, ...}) = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
close(3)                                = 0
chdir("/usr/share/netdata/web")         = 0
open("/usr/share/netdata/web", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat64(3, {st_mode=S_IFDIR|0755, st_size=419, ...}) = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
close(3)                                = 0
chdir("/var/cache/netdata")             = 0
open("/var/cache/netdata", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat64(3, {st_mode=S_IFDIR|0755, st_size=40, ...}) = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
brk(0x7c000)                            = 0x7c000
close(3)                                = 0
chdir("/var/lib/netdata")               = 0
open("/var/lib/netdata", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat64(3, {st_mode=S_IFDIR|0755, st_size=40, ...}) = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
close(3)                                = 0
chdir("/var/log/netdata")               = 0
open("/var/log/netdata", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat64(3, {st_mode=S_IFDIR|0755, st_size=40, ...}) = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
close(3)                                = 0
chdir("/etc/netdata")                   = 0
uname({sys="Linux", node="OpenWrt", ...}) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], NULL, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, ~[RTMIN RT_1], 0x4000000 /* SA_??? */}, NULL, 8) = 0
rt_sigaction(SIGINT, {0xde30, ~[RTMIN RT_1], 0x4000000 /* SA_??? */}, NULL, 8) = 0
rt_sigaction(SIGTERM, {0xde30, ~[RTMIN RT_1], 0x4000000 /* SA_??? */}, NULL, 8) = 0
rt_sigaction(SIGHUP, {0xde94, ~[RTMIN RT_1], 0x4000000 /* SA_??? */}, NULL, 8) = 0
rt_sigaction(SIGUSR1, {0xdee0, ~[RTMIN RT_1], 0x4000000 /* SA_??? */}, NULL, 8) = 0
rt_sigaction(SIGUSR2, {0xdf2c, ~[RTMIN RT_1], 0x4000000 /* SA_??? */}, NULL, 8) = 0
getuid32()                              = 0
open("/etc/passwd", O_RDONLY)           = 3
ioctl(3, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, 0xbeb827b4) = -1 ENOTTY (Inappropriate ioctl for device)
read(3, "root:x:0:0:root:/root:/bin/ash\nd"..., 4096) = 416
close(3)                                = 0
open("/etc/group", O_RDONLY)            = 3
ioctl(3, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, 0xbeb827b4) = -1 ENOTTY (Inappropriate ioctl for device)
read(3, "root:x:0:mvsysem,mvsys\ndaemon:x:"..., 4096) = 220
close(3)                                = 0
open("/etc/gai.conf", O_RDONLY)         = -1 ENOENT (No such file or directory)
socket(PF_INET6, SOCK_STREAM, IPPROTO_IP) = 3
setsockopt(3, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
setsockopt(3, SOL_IPV6, IPV6_V6ONLY, [1], 4) = 0
bind(3, {sa_family=AF_INET6, sin6_port=htons(19999), inet_pton(AF_INET6, "::", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = 0
listen(3, 100)                          = 0
socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 4
setsockopt(4, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(4, {sa_family=AF_INET, sin_port=htons(19999), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
listen(4, 100)                          = 0
open("/dev/null", O_WRONLY|O_CREAT|O_APPEND, 0664) = 5
dup2(5, 0)                              = 0
close(5)                                = 0
open("/dev/null", O_WRONLY|O_CREAT|O_APPEND, 0664) = 5
dup2(5, 1)                              = 1
close(5)                                = 0
open("/dev/null", O_WRONLY|O_CREAT|O_APPEND, 0664) = 5
dup2(5, 2)                              = 2
close(5)                                = 0
open("/dev/null", O_WRONLY|O_CREAT|O_APPEND, 0664) = 5
fcntl(5, F_GETFL)                       = 0x401 (flags O_WRONLY|O_APPEND)
ioctl(5, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, 0xbeb827e4) = -1 ENOTTY (Inappropriate ioctl for device)
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0xb6fd2068) = 2012
exit_group(0)                           = ?
+++ exited with 0 +++
root@OpenWrt:/#

**Comment by wbx-github** [comment]
The problem was identified by a missing directory after looking at strace -f output.
