### ISSUE TITLE
Compile fails with undeclared error in libuargp...

### ISSUE THREAD

**Issue by JonathanBelanger** [wbx-github/uclibc-ng#2]
My environment is:
```
Ubuntu 16.04
gcc 5.4.0
```
The error I am getting is:
```
  CC libuargp/argp-ba.os
  CC libuargp/argp-eexst.os
  CC libuargp/argp-fmtstream.os
  CC libuargp/argp-fs-xinl.os
  CC libuargp/argp-help.os
libuargp/argp-help.c In function '__argp_short_program_name':
libuargp/argp-help.c:1702:4: warning: #warning No reasonable value to return [-Wcpp]
 #  warning No reasonable value to return
libuargp/argp-help.c: At top level:
cc1: warning: unrecognized command line option '-Wno-nonnull-compare'
  CC libuargp/argp-parse.os
libuargp/argp-parse.c: In function 'argp_default_parser':
libuargp/argp-parse.c:116:7: error: 'program_invocation_name' undeclared (first use in this function)
       program_invocation_name = arg;
       ^
libuargp/argp-parse.c:116:7: note: each undeclared identifier is reported only once for each function it appears in
libuargp/argp-parse.c:130:7: error 'program_invocation_short_name' undeclared (first use in this function)
       program_invocation_short_name = state->name;
       ^
libuargp/argp-parse.c: At top level:
cc1: warning: unrecognized command line option '-Wno-nonnull-compare'
Makerules:369: recipe for target 'libuargp/argp-parse.os' failed
make: *** [libuargp/argp-parse.os] Error 1
```

**Comment by fallen** [comment]
Hello, 
Which version of uClibc-ng are you using? (git SHA1 ? patches you have applied?)
What is your uClibc-ng config?
Especially do you have  HAVE_DECL_PROGRAM_INVOCATION_NAME ?

Which libuargp are you compiling? the one included in uClibc-ng?

**Comment by JonathanBelanger** [comment]
I'm using 1.0.31.  I have not applied any patches.  I did the `allyesconfig`.  Yes, to the last two questions.  I'd love to be able to give more details but I'm doing this work an an air-gapped networks and thus cannot move information out of the network (just copy it into it).  So, I'm sorry for the delays.

**Comment by fallen** [comment]
Hello, 
I think you found a bug.
I guess that you don't have `UCLIBC_HAS_PROGRAM_INVOCATION_NAME=y` in your .config?

Can you please try this patch?

```diff
diff --git a/libuargp/argp-parse.c b/libuargp/argp-parse.c
index ecd5e7eb6..030bc4f9f 100644
--- a/libuargp/argp-parse.c
+++ b/libuargp/argp-parse.c
@@ -112,7 +112,7 @@ argp_default_parser (int key, char *arg, struct argp_state *state)
       break;
 
     case OPT_PROGNAME:         /* Set the program name.  */
-#if defined _LIBC || HAVE_DECL_PROGRAM_INVOCATION_NAME
+#if defined _LIBC && defined(__UCLIBC_HAS_PROGRAM_INVOCATION_NAME__)
       program_invocation_name = arg;
 #endif
       /* [Note that some systems only have PROGRAM_INVOCATION_SHORT_NAME (aka
@@ -126,7 +126,7 @@ argp_default_parser (int key, char *arg, struct argp_state *state)
       else
        state->name = arg;
 
-#if defined _LIBC || HAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME
+#if defined _LIBC && defined(__UCLIBC_HAS_PROGRAM_INVOCATION_NAME__)
       program_invocation_short_name = state->name;
 #endif
 ```

**Comment by fallen** [comment]
@JonathanBelanger Can you confirm if this patch solves your problem?

**Comment by JonathanBelanger** [comment]
I will wen I get back into the office on Monday.  We are in the process of moving and will be shutting everything down Monday afternoon and moving into the new place on Tuesday, so it may be a few days before I can get to this.

BTW: I'm in the process of converting this to use CMake instead of make.

**Comment by fallen** [comment]
Great! Ok I'll wait for your feedback before submitting the patch to the mailing list then.

**Comment by JonathanBelanger** [comment]
Wow your fast. :)

**Comment by JonathanBelanger** [comment]
Also, I have recently been playing with `allyesconfig` and `defconfig` and both of those appear to be working.  The issue croped up when I manually stepped through the configuration (non-GUI).

**Comment by fallen** [comment]
Ah, yes I've been wondering about this as well. I also thought that "allyesconfig" should have worked.

**Comment by JonathanBelanger** [comment]
Unfortunately not.  I'm generally building this package quite a few times per day.  When I was first starting with this I tried quite a few options, which unfortunately overwrote previous configurations.  Knowing about the ` HAVE_DECL_PROGRAM_INVOCATION_NAME ` and `UCLIBC_HAS_PROGRAM_INVOCATION_NAME`, I can take a look to see where and when these get set or not, and try to recreate the condition prior to patching and then again after patching.  I figure it may take me a few iterations to get it right.

**Comment by JonathanBelanger** [comment]
I figured out how I caused the problem.  I answered yes to including `argp` and take the defaults of everything else.  It does not matter if you use `config` or `menuconfig`.  Either way, the `UCLIBC_HAS_PROGRAM_INVOCATION_NAME` is commented out in the `.config` file.  The predefined config files are ok, because `HAS_ARGP` and `HAS_PROGRAM_...` are either defined or not defined together.  So, though your fix above is the correct one, it is not complete.  The `.config` generation needs to be updated to make sure that if `UCLIBC_HAS_ARGP` is set, that `UCLIBC_HAS_PROGRAM_INVOCATION_NAME` is also set.

**Comment by JonathanBelanger** [comment]
You could also, use if `UCLIBC_HAS_ARGP` is set and either `UCLIBC_HAS_PROGRAM_INVOCATION_NAME` is not defined or defined to 'n'.

**Comment by fallen** [comment]
I think that with my patch makes it so that you can set UCLIBC_HAS_ARGP and unset UCLIBC_HAS_PROGRAM_INVOCATION_NAME without the compilation (or runtime) to fail.

**Comment by fallen** [comment]
Can you confirm that with the patch posted in https://github.com/wbx-github/uclibc-ng/issues/2#issuecomment-498371832 it works even when UCLIBC_HAS_ARGP is set and UCLIBC_HAS_PROGRAM_INVOCATION_NAME is unset (or set)?

**Comment by JonathanBelanger** [comment]
Yes, I will.  I had a VM failure that took out all my work.  I'm recreating it now.

**Comment by JonathanBelanger** [comment]
OK, the compile does not fail but I get the following error (which is related to what I indicated above):
```
libuargp/argp-help.c: In function '__argp_short_program_name':
libuargp/argp-help.c:1702:4 warning: #warning No reasonable value to return [-Wcpp]
 #  warning No reasonable value to return
    ^
libuargp/argp-help.c: At top level:
cc1: warning unrecognized command line argument '-Wno-nonnull-compare'
```

**Comment by fallen** [comment]
Thanks for the test!
Ok, that looks reasonable to me.
If you don't select "program_invocation_name" you get a warning, but it compiles and it runs without crashing.
Looks OK to me.

**Comment by JonathanBelanger** [comment]
If that's how it's supposed to be, then I'll close this issue.  Thanks.

**Comment by fallen** [comment]
Fix has been pushed upstream: https://cgit.uclibc-ng.org/cgi/cgit/uclibc-ng.git/commit/?id=f93b43e4d1a02b72e8e7659f6be4cc28a0c6e194
Thanks for your report!
