### ISSUE TITLE
Compile fails with undeclared identifier 'MAP_UNINITIALIZED'

### ISSUE THREAD

**Issue by JonathanBelanger** [wbx-github/uclibc-ng#3]
When running `make allnoconfig` followed by `make`, I get the following compiler error:
```
libc/stdlib/malloc/malloc.c: In function'__malloc_from_heap':
libc/stdlib/malloc/malloc.c:127:36: error 'MAP_UNINITIALIZED' undeclared (first use in this function)
       MAP_SHARED | MAP_ANONYMOUS | MAP_UNINITIALIZED, 0, 0);
                                    ^
libc/stdlib/malloc/malloc.c:127:36: note: each undeclared identifier is reported only once for each function it appears in
libc/stdlib/malloc/malloc.c: At top level:
cc1: warning: unrecognized command line option '-Wno-nonnull-compare'
Makerules:368: recipe for target 'libc/stdlib/malloc/malloc.o' failed
make: *** [libc/stdlib/malloc/malloc.0] Error 1
```

**Comment by fallen** [comment]
Hello, 
Can you provide the .config?
Which target architecture are you compiling for?
Thanks!

**Comment by JonathanBelanger** [comment]
I'm actually on vacation and do not have access to the .config file.  All I did was run `make allnoconfig`, editted the .config file to contain the path to the kernel headers, then ran 'make'.  It was not much more than that.  Hopefully, this'll help.

**Comment by fallen** [comment]
Ok, so I guess this was done on x86_64 host? (so targeting x86_64).

**Comment by JonathanBelanger** [comment]
Yes, that is correct.  Running Ubuntu 16.04.

**Comment by fallen** [comment]
After a bit of investigation, it seems "allnoconfig" might not be well supported.
it seems you need to "know what you're doing" and not expect this to work "out of the box".
Basically, the "allnoconfig" selected x86_64 arch and didn't select "ARCH_USE_MMU".

I don't think that the x86_64 port is meant to support the "noMMU" configuration.
At least I would say it's a weird combination.

If you didn't really intend to not use the MMU, please activate it and try again.
Again, I get some error further down the compilation ...
Not sure "allnoconfig" is a good idea here.

**Comment by JonathanBelanger** [comment]
OK.  I'm not going to be building the `allnoconfig`.  Primarily the `allyesconfig` and the `defconfig`.  I'm closing this as functionality that should not be taken as is and requires a higher level of expertise.
