### ISSUE TITLE
Is there a test suite for uClibc that can be used against the statically built libc.a...

### ISSUE THREAD

**Issue by JonathanBelanger** [wbx-github/uclibc-ng#6]
I need to be able to test the build of uClibc, where only the static library libc.a is built (and not installed).  Is there such a thing?  Thanks.

**Comment by fallen** [comment]
Hello, 
I usually use this one https://cgit.uclibc-ng.org/cgi/cgit/uclibc-ng-test.git/ even for libc.a
If some test does not happen to compile, you can just delete it from the Makefiles.

**Comment by fallen** [comment]
If this issue is sorted out do not hesitate to close it :)

**Comment by JonathanBelanger** [comment]
I've moved on from this project, but made the changes in my work environment.  I no longer have access to those changes.  Sorry.
